SELECT TOP (1000) [StudentID]
      ,[FullName]
      ,[EnrollmentNo]
      ,[Email]
      ,[ContactNo]
      ,[DepartmentID]
      ,[SemesterID]
      ,[StudentImage]
      ,[StudentStatus]
      ,[CreatedDate]
      ,[UpdatedDate]
      ,[IsAct]
  FROM [LibraryDB].[dbo].[TblStudents]
